name: Playwright Tests

# Expanded permissions to allow GitHub Pages deployment for Allure static site
permissions:
  contents: read
  actions: read
  checks: write
  pages: write      # needed for pages deployment
  id-token: write   # required by actions/deploy-pages for OIDC

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Concurrency to avoid overlapping deployments of Pages site
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  api-tests:
    name: API Tests
    timeout-minutes: 30
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Generate BDD tests
      run: |
        echo "Generating BDD tests for API project"
        npm run bdd:gen
        echo "Generated files (API project filters via grep @api):"
        find .features-gen/api -name "*.js" -type f 2>/dev/null || echo "No API generated JS (expected if cached)"
    
    - name: Run API Tests
      run: |
        echo "Running API tests (default reporters: html + allure)"
        npx playwright test --project=api-tests
      env:
        CI: true
        API_BASE_URL: https://jsonplaceholder.typicode.com
    
    - name: Upload API test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: api-test-report
        path: playwright-report/
        retention-days: 30
        if-no-files-found: warn
    
    - name: Upload API Allure results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: api-allure-results
        path: allure-results/
        retention-days: 30
        if-no-files-found: warn
    
    - name: Upload API traces
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: api-test-traces
        path: test-results/
        retention-days: 30

  ui-tests:
    name: UI Tests
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: api-tests  # UI tests only run after API tests pass
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install chromium --with-deps
    
    - name: Generate BDD tests
      run: |
        echo "Generating BDD tests for UI project"
        npm run bdd:gen
        echo "Generated files (UI project filters via grep @ui):"
        find .features-gen/ui -name "*.js" -type f 2>/dev/null || echo "No UI generated JS (expected if cached)"
    
    - name: Run UI Tests
      run: |
        echo "Running UI tests (default reporters: html + allure)"
        npx playwright test --project=ui-tests
      env:
        CI: true
        BASE_URL: https://playwright.dev
    
    - name: Upload UI test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ui-test-report
        path: playwright-report/
        retention-days: 30
        if-no-files-found: warn
    
    - name: Upload UI Allure results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ui-allure-results
        path: allure-results/
        retention-days: 30
        if-no-files-found: warn
    
    - name: Upload UI traces
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: ui-test-traces
        path: test-results/
        retention-days: 30

  summary:
    name: Test Summary
    if: always()
    needs: [api-tests, ui-tests]
    runs-on: ubuntu-latest
    
    steps:
    - name: Test Results Summary
      run: |
        echo "## Test Results Summary" >> $GITHUB_STEP_SUMMARY
        echo "- API Tests: ${{ needs.api-tests.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- UI Tests: ${{ needs.ui-tests.result }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ "${{ needs.api-tests.result }}" = "success" ] && [ "${{ needs.ui-tests.result }}" = "success" ]; then
          echo "✅ All tests passed successfully!" >> $GITHUB_STEP_SUMMARY
        elif [ "${{ needs.api-tests.result }}" = "failure" ]; then
          echo "❌ API tests failed - UI tests were not executed" >> $GITHUB_STEP_SUMMARY
        elif [ "${{ needs.ui-tests.result }}" = "failure" ]; then
          echo "❌ UI tests failed - API tests passed" >> $GITHUB_STEP_SUMMARY
        else
          echo "⚠️  Some tests were skipped or cancelled" >> $GITHUB_STEP_SUMMARY
        fi

  publish-allure:
    name: Publish Allure Static Report
    if: always()
    needs: [api-tests, ui-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (for potential metadata)
        uses: actions/checkout@v4

      - name: Download API Allure results
        uses: actions/download-artifact@v4
        with:
          name: api-allure-results
          path: merged-allure/api
        if: always()

      - name: Download UI Allure results
        uses: actions/download-artifact@v4
        with:
          name: ui-allure-results
          path: merged-allure/ui
        if: always()

      - name: Merge Allure results
        run: |
          set -euo pipefail
          mkdir -p allure-results
          echo "Merging Allure results from API and UI runs"
          # Copy API results first
          if [ -d merged-allure/api ]; then
            cp -R merged-allure/api/. allure-results/
          fi
          # Copy UI results (may overwrite history files but that's acceptable for single-run merge)
            
          if [ -d merged-allure/ui ]; then
            cp -R merged-allure/ui/. allure-results/
          fi
          echo "Counts:" 
          echo " API result files: $(ls -1 merged-allure/api 2>/dev/null | wc -l || true)"
          echo " UI  result files: $(ls -1 merged-allure/ui 2>/dev/null | wc -l || true)"
          echo " Combined files: $(ls -1 allure-results 2>/dev/null | wc -l || true)"

      - name: Install Node (for allure commandline dependency)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Allure CLI
        run: |
          npm install --no-save allure-commandline@latest

      - name: Generate Allure static site
        run: |
          npx allure generate allure-results --clean -o allure-report

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report
        if: always()

  deploy-allure:
    name: Deploy Allure to GitHub Pages
    # Only attempt deployment on push events to default branches; still show if tests failed for visibility
    if: github.event_name == 'push'
    needs: publish-allure
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4